version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: netscope
      POSTGRES_USER: netscope
      POSTGRES_PASSWORD: netscope
    volumes:
      - pgdata:/var/lib/postgresql/data

  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream"]

volumes:
  pgdata:
